### PR TITLE
#162414176 Implement article readTimeCalculator function

### PR DESCRIPTION
**Pull request by eltNEG**
#### What does this PR do?
Implement read time calculator function and middleware for article content

#### Description of Task to be completed?
- implement a readTimeCalculator function for article content
- implement calculateReadTime middleware for article content

#### How should this be manually tested?
1. run `npm test`

#### Any background context you want to provide?
This middleware is meant to be used after the articleValidator middleware. This is to ensure that article content is validated before being passed to this middleware.

#### What are the relevant pivotal tracker stories?
PT Link: https://www.pivotaltracker.com/story/show/162414176

### CODE REVIEW

**Review by iAfolayan — DISMISSED** [review]

**Comment by Maxfurry** [comment]
Please, how can I manually test this solution you provided, running npm test will not show me how it functions or see if it works. Thanks.

**Review by iMichaelOwolabi — DISMISSED** [review]
Nice job

**Review by codrex — COMMENTED** [review]
Nice work so far. But I feel you have not completed the task. Read time should only be computed twice, during article creation and update and result from the computation be stored on the article table.

**Comment by eltNEG** [comment]
> Nice work so far. But I feel you have not completed the task. Read time should only be computed twice, during article creation and update and result from the computation be stored on the article table.

Yes @codrex. The article controller has not been merged yet. The function can be used in the post article and put article route after it has been merged. Or should I make it a middleware?

**Review by iAfolayan — DISMISSED** [review]

**Comment by codrex** [comment]
ok

**Review by codrex — APPROVED** [review]

**Pull request merged**
